BLUTWERTE = [
    'CD36',  # lutein BCMO1 Vitamin A mangel Toxoplasma Malaria
    'CD43',  # B-Zellen Antikörper produktion
    '(ALAT [Title/Abstract] OR GPT[Title/Abstract])',
    '(ASAT [Title/Abstract] OR GOT[Title/Abstract])',
    '(GGT [Title/Abstract])',
    'ANCA [Title/Abstract]',
    'basophil[Title/Abstract]',
    'bilirubin[Title/Abstract]',
    'C7 -[Title/Abstract]',
    'CA 125[Title/Abstract]',
    'CA19-9[Title/Abstract]',
    'CA242[Title/Abstract]',
    'CA50[Title/Abstract]',
    'CA72-4[Title/Abstract]',
    'CD133+[Title/Abstract]',
    'CD19+[Title/Abstract]',
    'CD23[Title/Abstract]',
    'CD25[Title/Abstract]',
    'CD28+[Title/Abstract]',
    'CD3+[Title/Abstract]',
    'CD34+[Title/Abstract]',
    'CD4+[Title/Abstract]',
    'CD45RA+[Title/Abstract]',
    'CD45RO+[Title/Abstract]',
    'CD56',
    'CD5[Title/Abstract]',
    'CD69[Title/Abstract]',
    'CD8+[Title/Abstract]',
    'CD8-[Title/Abstract]',
    'Cross-Reactivity[Title/Abstract]',
    'CEA[Title/Abstract]',
    'DUPAN-2[Title/Abstract]',
    'factor X [Title/Abstract]',
    'ferritin',
    'GPT [Title/Abstract]',
    'IL-10[Title/Abstract]',
    'IL-12[Title/Abstract]',
    'IL-13[Title/Abstract]',
    'IL-17[Title/Abstract]',
    'IL-23[Title/Abstract]',
    'IL-6[Title/Abstract]',
    'IL-7[Title/Abstract]',
    'IL-8[Title/Abstract]',
    'LDH [Title/Abstract]',
    'lymphocytes [Title/Abstract]',
    'MCHC [Title/Abstract]',
    'MCV [Title/Abstract]',
    'monocyte [Title/Abstract]',
    'neutrophil [Title/Abstract]',
    'nk cell[Title/Abstract]',
    'NSE [Title/Abstract]',
    'RDW [Title/Abstract]',
    'RT3[Title/Abstract]',
    'RT4[Title/Abstract]',
    'Span-1[Title/Abstract]',
    'T3[Title/Abstract]',
    'T4[Title/Abstract]',
    'TCC [Title/Abstract]',
    'thrombocyte[Title/Abstract]',
    'TNF-alpha[Title/Abstract]',
]

MEDIKAMENTE = [
    '(Artemisia [Title/Abstract] OR artemisinin[Title/Abstract])',
    'Abacavir [Title/Abstract]',
    'Abatacept[Title/Abstract]',
    'Albendazol[Title/Abstract]',
    'Amantadine[Title/Abstract]',
    'amaranth [Title/Abstract]',
    'Amlodipin[Title/Abstract]',
    'amoxicillin[Title/Abstract]',
    'Ampicillin[Title/Abstract]',
    'Aprepitant [Title/Abstract]',
    'artesunate [Title/Abstract]',
    'Atoltivimab [Title/Abstract]',
    'Atovaquon[Title/Abstract]',
    'Aziclovir[Title/Abstract]',
    'Azithromicin[Title/Abstract]',
    'Borrelidin',
    'Budesonide [Title/Abstract]',
    'Candesartan[Title/Abstract]',
    'cefazolin[Title/Abstract]',
    'cefoperazone [Title/Abstract]',
    'Cefotaxim[Title/Abstract]',
    'cefoxitin [Title/Abstract]',
    'Ceftazidim [Title/Abstract]',
    'ceftazidime [Title/Abstract]',
    'Cefuroxim [Title/Abstract]',
    'Cetirizin [Title/Abstract]',
    'Ceftriaxon[Title/Abstract]',
    'Cidofovir[Title/Abstract]',
    'cimetidin [Title/Abstract]',
    'clarithromycin [Title/Abstract]',
    'Clindamycin[Title/Abstract]',
    'Clofazimine[Title/Abstract]',
    'Cotrimoxazol[Title/Abstract]',
    'Daptomycin [Title/Abstract]',
    'darunavir[Title/Abstract]',
    'Diethylcarbamazine [Title/Abstract]',
    'disulfiram [Title/Abstract]',
    'DMSO [Title/Abstract]',
    'doxycyclin [Title/Abstract]',
    'Ertapenem [Title/Abstract]',
    'Erythromycin [Title/Abstract]',
    'Flucloxacillin [Title/Abstract]',
    'fluoride [Title/Abstract]',
    'Fluorouracil[Title/Abstract]',
    'fluvastatin[Title/Abstract]',
    'Formoterol [Title/Abstract]',
    'Fosfomycin [Title/Abstract]',
    'Gentamicin [Title/Abstract]',
    'Ibuprofen[Title/Abstract]',
    'Indometacin [Title/Abstract]',
    'Itraconazol[Title/Abstract]',
    'ivermectin[Title/Abstract]',
    'Ledipasvir [Title/Abstract]',
    'lidocaine[Title/Abstract]',
    'Linezolid[Title/Abstract]',
    'loratadine[Title/Abstract]',
    'Maftivimab [Title/Abstract]',
    'Malarone[Title/Abstract]',
    'mebendazole[Title/Abstract]',
    'Meropenem[Title/Abstract]',
    'Methylene Blue[Title/Abstract]',
    'Metronidazol[Title/Abstract]',
    'mirtazapin[Title/Abstract]',
    'Naltrexon [Title/Abstract]',
    'Neomycin [Title/Abstract]',
    'Niclosamid [Title/Abstract]',
    'nitrofurantoin[Title/Abstract]',
    'Nystatin [Title/Abstract]',
    'Odesivimab [Title/Abstract]',
    'omnadin [Title/Abstract]',
    'omoprazol[Title/Abstract]',
    'ondansetron [Title/Abstract]',
    'Piperacillin[Title/Abstract]',
    'Pradimicin A[Title/Abstract]',
    'Praziquantel[Title/Abstract]',
    'Prednisolon[Title/Abstract]',
    'Proguanil[Title/Abstract]',
    'Pyrantelembonat [Title/Abstract]',
    'Pyrazinamid [Title/Abstract]',
    'Pyrimethamin[Title/Abstract]',
    'Pyrvinium [Title/Abstract]',
    'Pyrviniumembonat [Title/Abstract]',
    'ramipril[Title/Abstract]',
    'rifampicin[Title/Abstract]',
    'Rosuvastatin [Title/Abstract]',
    'Sofosbuvir[Title/Abstract]',
    'Sulbactam[Title/Abstract]',
    'Tafenoquin[Title/Abstract]',
    'Tazobactam[Title/Abstract]',
    'Teicoplanin[Title/Abstract]',
    'Tenofovir[Title/Abstract]',
    'tetracycline[Title/Abstract]',
    'Tigecyclin[Title/Abstract]',
    'Tobramycin[Title/Abstract]',
    'Toltrazuril[Title/Abstract]',
    'Trimethoprim[Title/Abstract]',
    'valsartan[Title/Abstract]',
    'Vancomycin [Title/Abstract]',
    'Verteporfin[Title/Abstract]',
]

KRANKHEITEN = [
    '(Cytomegalovirus[Title/Abstract] OR CMV[Title/Abstract])',
    '(Epstein-Barr[Title/Abstract] OR EBV [Title/Abstract])',
    '(JCV[Title/Abstract] OR JC Virus [Title/Abstract])',
    '(Lyme [Title/Abstract] OR Borrelia[Title/Abstract])',
    '(Toxoplasmosis [Title/Abstract] OR Toxoplasma[Title/Abstract])',
    '(varicella zoster [Title/Abstract] OR VZV [Title/Abstract])',
    'Alaria alata',
    'Anaplasma [Title/Abstract]',
    'Ancylostoma [Title/Abstract]',
    'Anisakis [Title/Abstract]',
    'Ascaris [Title/Abstract]',
    'Babesia [Title/Abstract]',
    'Herniaria [Title/Abstract]',
    'bacteria[Title/Abstract]',
    'Bartonella [Title/Abstract]',
    'Borna [Title/Abstract]',
    'botrytis[Title/Abstract]',
    'brucella[Title/Abstract]',
    'Burkholderia[Title/Abstract]',
    'Brugia[Title/Abstract]',
    'Camphylobacter[Title/Abstract]',
    'Candida [Title/Abstract]',
    'chlamydia [Title/Abstract]',
    'choriomeningitis [Title/Abstract]',
    'Clonorchis  [Title/Abstract]',
    'Coronavirus [Title/Abstract]',
    'Cryptococcus[Title/Abstract]',
    'Dicrocoelium [Title/Abstract]',
    'Diphyllobothrium latum [Title/Abstract]',
    'Dracunculus [Title/Abstract]',
    'Echo virus [Title/Abstract]',
    'Ehlers-Danlos [Title/Abstract]',
    'Ehrlichia [Title/Abstract]',
    'Entamoeba [Title/Abstract]',
    'Enterobius vermicularis [Title/Abstract]',
    'Echinococcus [Title/Abstract]',
    'Fasciola [Title/Abstract]',
    'Francisella [Title/Abstract]',
    'giardia [Title/Abstract]',
    'Helicobacter pylori [Title/Abstract]',
    'Hepatitis [Title/Abstract]',
    'herpes [Title/Abstract]',
    'HIV [Title/Abstract]',
    'HSV [Title/Abstract]',
    'Hymenolepis [Title/Abstract]',
    'hypothyroidism  [Title/Abstract]',
    'klebsiella [Title/Abstract]',
    'Leishmania [Title/Abstract]',
    'Linguatula serrata [Title/Abstract]',
    'Listeria [Title/Abstract]',
    'lyssavirus [Title/Abstract]',
    'Malaria [Title/Abstract]',
    'metagenomic [Title/Abstract]',
    'Microsporum canis [Title/Abstract]',
    'Mycoplasma [Title/Abstract]',
    'Mycobacterium [Title/Abstract]',
    'Necator [Title/Abstract]',
    'NDM-1 [Title/Abstract]',
    'Neorickettsia [Title/Abstract]',
    'Orientia [Title/Abstract]',
    'Onchocerca [Title/Abstract]',
    'Paragonimus Westermania [Title/Abstract]',
    'parasite [Title/Abstract]',
    'pertussis [Title/Abstract]',
    'phagocytophilum [Title/Abstract]',
    'Plasmodium[Title/Abstract]',
    'Pseudomonas[Title/Abstract]',
    'Pneumocystsis carinii [Title/Abstract]',
    'polyomavirus [Title/Abstract]',
    'rhizopus [Title/Abstract]',
    'Rickettsia [Title/Abstract]',
    'Schistosoma [Title/Abstract]',
    'stachybotris [Title/Abstract]',
    'Staphylococcus [Title/Abstract]',
    'Streptococcus [Title/Abstract]',
    'Strongyloides [Title/Abstract]',
    'syphilis [Title/Abstract]',
    'Taenia saginata [Title/Abstract]',
    'Taenia solium [Title/Abstract]',
    'Trichobilharzia szidati [Title/Abstract]',
    'Tropheryma [Title/Abstract]',
    'Trypanosoma [Title/Abstract]',
    'Torque teno [Title/Abstract]',
    'Trichuris [Title/Abstract]',
    'tuberculosis[Title/Abstract]',
    'Tularaemia [Title/Abstract]',
    'virus[Title/Abstract]',
    'Wuchereria[Title/Abstract]',
    'Yersinia[Title/Abstract]',
    'Wolbachia [Title/Abstract]',
]

CODEWOERTER = [
    'Cross-Reactivity',
    'deficiency',
    'low',
    'marker',
    'therapy',
]

PFLANZEN = [
    '(plant [Title/Abstract]OR herb[Title/Abstract]OR herbal[Title/Abstract])',
    'Adhatoda vasica [Title/Abstract]',
    'Adhatoda vasica[Title/Abstract]',
    'Aegle marmelos [Title/Abstract]',
    'Agastache rugosa[Title/Abstract]',
    'Alangium chinense[Title/Abstract]',
    'Alchornea cordifolia[Title/Abstract]',
    'Allicin [Title/Abstract]',
    'Allium [Title/Abstract]',
    'Aloe vera [Title/Abstract]',
    'Amaranthus [Title/Abstract]',
    'Andrographis paniculata[Title/Abstract]',
    'Anemarrhenae[Title/Abstract]',
    'Anemone chinensis [Title/Abstract]',
    'Angelica [Title/Abstract]',
    'Anisodus tanguticus[Title/Abstract]',
    'Arctium [Title/Abstract]',
    'Ardisia japonica[Title/Abstract]',
    'Aster tataricus[Title/Abstract]',
    'Astragalus propinquus [Title/Abstract]',
    'Astragalus [Title/Abstract]',
    'Atractylodes [Title/Abstract]',
    'Arctostaphylos[Title/Abstract]',
    'baicalin [Title/Abstract]',
    'Balanite aegyptica[Title/Abstract]',
    'bartericin [Title/Abstract]',
    'Berberis vulgari[Title/Abstract]',
    'Boesenbergia rotunda[Title/Abstract]',
    'Bupleurum chinense [Title/Abstract]',
    'Calotropis procera [Title/Abstract]',
    'Camellia sinensis[Title/Abstract]',
    'Cannabis sativa[Title/Abstract]',
    'Canavalia [Title/Abstract]',
    'capsidium[Title/Abstract]',
    'Carthamus tinctorius[Title/Abstract]',
    'Cassia [Title/Abstract]',
    'Cinnamomum cassia[Title/Abstract]',
    'Cissampelos pareira[Title/Abstract]',
    'Cistus [Title/Abstract]',
    'Citrus [Title/Abstract]',
    'Coix [Title/Abstract]',
    'Coptis chinensis[Title/Abstract]',
    'Coriandrum [Title/Abstract]',
    'Corydalis ambigua[Title/Abstract]',
    'Crataegus [Title/Abstract]',
    'Croton tiglium[Title/Abstract]',
    'Cryptolepis[Title/Abstract]',
    'Curcuma [Title/Abstract]',
    'curcumin [Title/Abstract]',
    'Ceratonia [Title/Abstract]',
    'Cymbopogon martini[Title/Abstract]',
    'Daphne genkwa[Title/Abstract]',
    'Datura [Title/Abstract]',
    'Dendrobium [Title/Abstract]',
    'Dichroa febrifuga[Title/Abstract]',
    'dihydrokaempferol[Title/Abstract]',
    'diprenyleriodictyol[Title/Abstract]',
    'Dipsacus [Title/Abstract]',
    'Echinacea[Title/Abstract]',
    'Eclipta alba[Title/Abstract]',
    'Eiekikaryu [Title/Abstract]',
    'Elettaria cardamomum[Title/Abstract]',
    'Ephedra sinica[Title/Abstract]',
    'Eucommia ulmoides[Title/Abstract]',
    'Eucommiae Cortex [Title/Abstract]',
    'Eugenia caryophyllata[Title/Abstract]',
    'Euphorbia pekinensis[Title/Abstract]',
    'Fagopyrum cymosum[Title/Abstract]',
    'Flueggea suffruticosa[Title/Abstract]',
    'Foeniculum [Title/Abstract]',
    'Fomes fomentarius [Title/Abstract]',
    'Forsythia suspensa[Title/Abstract]',
    'galangin [Title/Abstract]',
    'Gentiana [Title/Abstract]',
    'Gleditsia sinensis[Title/Abstract]',
    'Glycyrrhiza [Title/Abstract]',
    'Glyptopetalum calocarpum[Title/Abstract]',
    'Grapefruit[Title/Abstract]',
    'Gynostemma pentaphyllum[Title/Abstract]',
    'Gynura procumbens[Title/Abstract]',
    'Hericium [Title/Abstract]',
    'Hesperetin[Title/Abstract]',
    'Hydnocarpus anthelminticus[Title/Abstract]',
    'hydroxylupinifolinol [Title/Abstract]',
    'Hypericum perforatum[Title/Abstract]',
    'Ilex purpurea[Title/Abstract]',
    'Illicium verum[Title/Abstract]',
    'indica [Title/Abstract]',
    'Inonotus obliquus[Title/Abstract]',
    'isobavachalcone [Title/Abstract]',
    'Juglans nigra[Title/Abstract]',
    'Launaea [Title/Abstract]',
    'Leonurus japonicus[Title/Abstract]',
    'licochalcone [Title/Abstract]',
    'Ligusticum [Title/Abstract]',
    'Lobelia chinensis[Title/Abstract]',
    'Lycium [Title/Abstract]',
    'Magnoliae Officinalis [Title/Abstract]',
    'Mentha piperita[Title/Abstract]',
    'methyldiplacol [Title/Abstract]',
    'Momordica[Title/Abstract]',
    'Monolaurin[Title/Abstract]',
    'naringenin [Title/Abstract]',
    'Nigella sativa[Title/Abstract]',
    'Nyctanthes arbor-tristis[Title/Abstract]',
    'Oldenlandia [Title/Abstract]',
    'Oregano[Title/Abstract]',
    'Otoba parvifolia[Title/Abstract]',
    'Panax [Title/Abstract]',
    'panduratin [Title/Abstract]',
    'Paulownia tomentosa',
    'Peganum [Title/Abstract]',
    'Petasites [Title/Abstract]',
    'Phellodendron amurense[Title/Abstract]',
    'Pongamia[Title/Abstract]',
    'phloretin [Title/Abstract]',
    'Picrorhiza [Title/Abstract]',
    'pinocembrin [Title/Abstract]',
    'Piper nigrum[Title/Abstract]',
    'Platycladus orientalis[Title/Abstract]',
    'Polygonum cuspidatum[Title/Abstract]',
    'populus balsamifera[Title/Abstract]',
    'Poria [Title/Abstract]',
    'Pseudolarix amabilis[Title/Abstract]',
    'Pseudostellariae [Title/Abstract]',
    'Psilopeganum sinense[Title/Abstract]',
    'Pueraria lobata[Title/Abstract]',
    'Quercus infectoria[Title/Abstract]',
    'Rauwolfia serpentina[Title/Abstract]',
    'Rehmannia glutinosa[Title/Abstract]',
    'Resveratrol [Title/Abstract]',
    'rhamnoisorobin [Title/Abstract]',
    'Rheum officinale[Title/Abstract]',
    'Rhodiola [Title/Abstract]',
    'Rhododendron tsinghaiense[Title/Abstract]',
    'Rhus coriaria[Title/Abstract]',
    'Rosmarinic[Title/Abstract]',
    'rutin [Title/Abstract]',
    'Salvia [Title/Abstract]',
    'Saposhnikoviae [Title/Abstract]',
    'Satureja [Title/Abstract]',
    'Saussurea costus[Title/Abstract]',
    'Schisandra [Title/Abstract]',
    'Scutellaria[Title/Abstract]',
    'Shizonepeta[Title/Abstract]',
    'Sideritis angustifolia[Title/Abstract]',
    'Stachys schtschegleevii[Title/Abstract]',
    'Stemona tuberosa[Title/Abstract]',
    'Stephania tetrandra[Title/Abstract]',
    'Stevia rebaudiana[Title/Abstract]',
    'Styphnolobium japonicum [Title/Abstract]',
    'Terminalia [Title/Abstract]',
    'Thalictrum[Title/Abstract]',
    'Thapsia [Title/Abstract]',
    'Thymus[Title/Abstract]',
    'Tinospora [Title/Abstract]',
    'Tragia involucrata[Title/Abstract]',
    'Taraxacum[Title/Abstract]',
    'Trichosanthes kirilowii[Title/Abstract]',
    'Uncaria tomentosa[Title/Abstract]',
    'Urtica [Title/Abstract]',
    'Vernonia amygdalina [Title/Abstract]',
    'Vitamin C[Title/Abstract]',
    'Vitamin D3[Title/Abstract]',
    'Wikstroemia indica [Title/Abstract]',
    'Zingiber [Title/Abstract]',
]

HAUPTGENETIK = [
    'ACAT1[Title/Abstract]',
    'ANK3[Title/Abstract]',
    'BCMO1[Title/Abstract]',
    'BHMT[Title/Abstract]',
    'CACNA1C[Title/Abstract]',
    'FUT2[Title/Abstract]',
    'MMAB[Title/Abstract]',
    'MTHFR[Title/Abstract]',
    'MTRR[Title/Abstract]',
    'NDUFS3[Title/Abstract]',
    'NDUFS4[Title/Abstract]',
    'NDUFS5[Title/Abstract]',
    'NDUFS6[Title/Abstract]',
    'NDUFS7[Title/Abstract]',
    'NDUFS8[Title/Abstract]',
    'SOD2[Title/Abstract]',
    'PEMT [Title/Abstract]',
    'PSPH [Title/Abstract]',
    'SLC1A4 [Title/Abstract]',
    'SLC6A5 [Title/Abstract]',
    'SLC6A9 [Title/Abstract]',
    'GRIN2A [Title/Abstract]',
    'GRIN2B [Title/Abstract]',
    'FTO [Title/Abstract]',
    'PLIN1 [Title/Abstract]',
    'TRAP2B [Title/Abstract]',
    'BDNF [Title/Abstract]',
    'SLC23A1 [Title/Abstract]',
    'LPL [Title/Abstract]',
    'PDXK [Title/Abstract]',
]

VITAMIN = [
    '(bor [Title/Abstract] or boron [Title/Abstract] OR borax [Title/Abstract])',
    '(caprylic acid[Title/Abstract] or octanoic acid [Title/Abstract])',
    '(Histidin [Title/Abstract] OR Spermidin [Title/Abstract])',
    '(kalium [Title/Abstract] or Potassium [Title/Abstract])',
    '(mangan [Title/Abstract] OR manganese [Title/Abstract])',
    '(Omega 3[Title/Abstract] OR EPA [Title/Abstract]OR DHA [Title/Abstract])',
    '(Omega 6[Title/Abstract])',
    '(p-aminobenzoic acid [Title/Abstract]OR PABA [Title/Abstract])',
    '(plant [Title/Abstract]OR herb[Title/Abstract])',
    '(Q10 [Title/Abstract] or Quinol [Title/Abstract])',
    '(tetrahydrobiopterin [Title/Abstract] or BH4 [Title/Abstract])',
    '(Thiocyanate[Title/Abstract]OR Rhodanide[Title/Abstract])',
    '(Vitamin A [Title/Abstract] OR Retinol [Title/Abstract])',
    '(Vitamin B1 [Title/Abstract] OR Thiamin [Title/Abstract])',
    '(vitamin B12 [Title/Abstract] or Cobalamine [Title/Abstract] Or Aquocobalamin [Title/Abstract] OR Hydroxocobalamin [Title/Abstract] or Nitritocobalamin [Title/Abstract] OR Methylcobalamin [Title/Abstract])',
    '(Vitamin B2 [Title/Abstract] OR Riboflavin[Title/Abstract] OR Lactoflavin [Title/Abstract])',
    '(Vitamin B3 [Title/Abstract] OR NIACIN[Title/Abstract] OR nicotinic[Title/Abstract])',
    '(Vitamin B4 [Title/Abstract] OR cholin[Title/Abstract])',
    '(vitamin B5 [Title/Abstract] or pantothenic acid [Title/Abstract])',
    '(vitamin B6 [Title/Abstract] or Pyridoxamin[Title/Abstract] OR Pyridoxal [Title/Abstract]OR Pyridoxin[Title/Abstract]) ',
    '(vitamin B7 [Title/Abstract] or biotin [Title/Abstract] Vitamin H [Title/Abstract])',
    '(vitamin B9 [Title/Abstract] or Folic acid[Title/Abstract] OR methylfolate [Title/Abstract] )',
    '(Vitamin E [Title/Abstract]OR tocotrienol [Title/Abstract] OR Tocoferol[Title/Abstract] )',
    'alanine [Title/Abstract]',
    'anthocyanin [Title/Abstract]',
    'Apigenin [Title/Abstract]',
    'arginin [Title/Abstract]',
    'bacteria [Title/Abstract]',
    'calcium [Title/Abstract]',
    'carnitine [Title/Abstract]',
    'chlorid [Title/Abstract]',
    'chrom [Title/Abstract]',
    'Chrysin [Title/Abstract]',
    'citrulin [Title/Abstract]',
    'cobalt [Title/Abstract]',
    'copper [Title/Abstract]',
    'creatine [Title/Abstract]',
    'Cystein [Title/Abstract]',
    'd-alanine [Title/Abstract]',
    'D-Methionine [Title/Abstract]',
    'D-Phenylalanin [Title/Abstract]',
    'd-serin [Title/Abstract]',
    'D-Threonin [Title/Abstract]',
    'D-Tryptophan [Title/Abstract]',
    'Diosmin[Title/Abstract]',
    'ferritin [Title/Abstract]',
    'fluor [Title/Abstract]',
    'Fluoride [Title/Abstract]',
    'Glucan[Title/Abstract]',
    'glutamine [Title/Abstract]',
    'Glycin [Title/Abstract]',
    'hesperidin [Title/Abstract]',
    'hyaluronan [Title/Abstract]',
    'inositol [Title/Abstract]',
    'Iodine [Title/Abstract]',
    'Iron [Title/Abstract]',
    'Isoleucin [Title/Abstract]',
    'lauric acid [Title/Abstract]',
    'leucin [Title/Abstract]',
    'lipoic [Title/Abstract]',
    'lithium [Title/Abstract]',
    'Lutein [Title/Abstract]',
    'Luteolin [Title/Abstract]',
    'lysin [Title/Abstract]',
    'magnesium [Title/Abstract]',
    'Methionine [Title/Abstract]',
    'molybdenum [Title/Abstract]',
    'Myricetin [Title/Abstract]',
    'natrium [Title/Abstract]',
    'nickel [Title/Abstract]',
    'Ornithin [Title/Abstract]',
    'Phenylalanin [Title/Abstract]',
    'Phenylbutyrate [Title/Abstract]',
    'Phosphatidylcholine [Title/Abstract]',
    'phosphor [Title/Abstract]',
    'prolin [Title/Abstract]',
    'Quercetin [Title/Abstract]',
    'rubidium [Title/Abstract]',
    'Rutin [Title/Abstract]',
    'selen [Title/Abstract]',
    'serin [Title/Abstract]',
    'silicium [Title/Abstract]',
    'sulfur [Title/Abstract]',
    'Taurin [Title/Abstract]',
    'Taxifolin [Title/Abstract]',
    'Threonin [Title/Abstract]',
    'Tryptophan [Title/Abstract]',
    'valin [Title/Abstract]',
    'vanadium [Title/Abstract]',
    'Vitamin C [Title/Abstract]',
    'Vitamin D [Title/Abstract]',
    'vitamin K [Title/Abstract]',
    'zinc [Title/Abstract]',
]

GUTEBAKTERIEN = [
    'Akkermansia muciniphila[Title/Abstract]',
    'Acetobacteraceae [Title/Abstract]',
    'Acetobacter aceti[Title/Abstract]',
    'Acetobacter pasteurianus[Title/Abstract]',
    'Gluconobacter oxydans[Title/Abstract]',
    'Acetobacter orleanensis[Title/Abstract]',
    'Acetobacter tropicalis[Title/Abstract]',
    'Acetobacter syzygii[Title/Abstract]',
    'Acetobacter xylinum[Title/Abstract]',
    'Acetobacter xylinus[Title/Abstract]',
    'Bacteroides caccae[Title/Abstract]',
    'Bacteroides coprosuis[Title/Abstract]',
    'Bacteroides distasonis[Title/Abstract]',
    'Bacteroides fragilis[Title/Abstract]',
    'Bacteroides ovatus[Title/Abstract]',
    'Bacteroides thetaiotaomicron[Title/Abstract]',
    'Bacteroides uniformis[Title/Abstract]',
    'Bacteroides vulgatus[Title/Abstract]',
    'Bacteroides xylanisolvens[Title/Abstract]',
    'Bifidobacterium adolescentis[Title/Abstract]',
    'Bifidobacterium animalis[Title/Abstract]',
    'Bifidobacterium bifidum[Title/Abstract]',
    'Bifidobacterium breve[Title/Abstract]',
    'Bifidobacterium infantis[Title/Abstract]',
    'Bifidobacterium lactis[Title/Abstract]',
    'Bifidobacterium longum[Title/Abstract]',
    'Bifidobacterium pseudolongum[Title/Abstract]',
    'Bifidobacterium [Title/Abstract]',
    'Bifidobacterium animalis subsp. lactis BB-12',
    'Blautia producta[Title/Abstract]',
    'Clostridium butyricum[Title/Abstract]',
    'Clostridium coccoides[Title/Abstract]',
    'Clostridium difficile[Title/Abstract]',
    'Clostridium hylemonae[Title/Abstract]',
    'Clostridium perfringens[Title/Abstract]',
    'Clostridium ramosum[Title/Abstract]',
    'Clostridium scindens[Title/Abstract]',
    'Clostridium sporogenes[Title/Abstract]',
    'Eubacterium rectale[Title/Abstract]',
    'Faecalibacterium prausnitzii[Title/Abstract]',
    'Lactobacillus acidophilus[Title/Abstract]',
    'Lactobacillus casei[Title/Abstract]',
    'Lactobacillus crispatus[Title/Abstract]',
    'Lactobacillus fermentum[Title/Abstract]',
    'Lactobacillus gasseri[Title/Abstract]',
    'Lactobacillus paracasei[Title/Abstract]',
    'Lactobacillus plantarum[Title/Abstract]',
    'lactobacillus reuteri[Title/Abstract]',
    'Lactobacillus rhamnosus[Title/Abstract]',
    'Lactobacillus salivarius[Title/Abstract]',
    'Lactobacillus[Title/Abstract]',
    'lactobazillus remnosum GG[Title/Abstract]',
    'Lactococcus lactis[Title/Abstract]',
    'Parabacteroides distasonis[Title/Abstract]',
    'Roseburia intestinalis[Title/Abstract]',
    'Ruminococcus gnavus[Title/Abstract]',
    'Ruminococcus torques[Title/Abstract]',
    'Saccharomyces boulardii[Title/Abstract]',
    'Saccharomyces cerevisiae[Title/Abstract]',
]

ENZYME = [
    'CYP2C9[Title/Abstract]',
    'CYP2C19[Title/Abstract]',
    'CYP2D6[Title/Abstract]',
    'CYP3A4[Title/Abstract]',
    'CYP1A2[Title/Abstract]',
]

MINERALIEN = [
    'Chrom[Title/Abstract]',
    'Arsenic [Title/Abstract]',
    'Iodine[Title/Abstract]',
    'Iron[Title/Abstract]',
    'molybdenum[Title/Abstract]',
    'Zinc[Title/Abstract]',
    'Natrium[Title/Abstract]',
    'potash[Title/Abstract]',
    'phosphorus[Title/Abstract]',
]

AMINOSAEUREN = []
